version: "3"

volumes:
    volume_account_mongo:
    volume_account_s3:

secrets:
    MONGO_PASSWORD:
        file: secrets/mongo-password
    MONGO_URL:
        file: secrets/mongo-url
    JWT_SECRET_PHRASE:
        file: secrets/jwt-secret

networks:
    network_account_database:
    network_account_s3:
          
services:

    account-mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - volume_account_mongo:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_PASSWORD
        secrets:
            - MONGO_PASSWORD
        networks:
            - network_account_database

    account-s3:
        image: lphoward/fake-s3
        restart: always
        ports:
            - 4569:4569
        volumes:
            - volume_account_s3:/fakes3_root
        networks:
            - network_account_s3

    account-api:
        image: pcandido/ms-account
        build: .
        restart: always
        depends_on:
            - account-mongo
            - account-s3
        ports: 
            - 3000:3000
        environment:
            PORT: 3000
            S3_ENDPOINT: http://account-s3:4569
        secrets:
            - MONGO_URL
            - JWT_SECRET_PHRASE
        networks:
            - network_account_database
            - network_account_s3
          
