@startuml password-reset

package controllers {
    [PasswordResetController] -> () Validator
    [passwordResetValidator] -.-> () Validator
}

package domain {
    () PasswordReset
}

package usecase {
    () TokenDecoder <-- [PasswordResetUseCase]
    () LoadAccountByEmailRepository <-- [PasswordResetUseCase]
    () EmailSender <-- [PasswordResetUseCase]
}

package gateway {
    [JwtAdapter]
    [AccountMongoRepository]
    [EmailQueueAdapter]
}

PasswordResetController --> PasswordReset
PasswordResetUseCase -.-> PasswordReset
AccountMongoRepository -.-> LoadAccountByEmailRepository
JwtAdapter -.-> TokenDecoder
EmailQueueAdapter -.-> EmailSender

@enduml
