@startuml password-recovery

package controllers {
    [PasswordRecoveryController] -> () Validator
    [passwordRecoveryValidator] -.-> () Validator
    [passwordRecoveryValidator] -> () EmailValidator
}

package utils {
    [EmailValidatorAdapter]
}

package domain {
    () PasswordRecovery
}

package usecase {
    () LoadAccountByEmailRepository <-- [PasswordRecoveryUseCase]
    () TokenGenerator <-- [PasswordRecoveryUseCase]
    () EmailSender <-- [PasswordRecoveryUseCase]
}

package gateway {
    [AccountMongoRepository]
    [EmailQueueAdapter]
    [JwtAdapter]
}

EmailValidatorAdapter -.-> EmailValidator
PasswordRecoveryController --> PasswordRecovery
PasswordRecoveryUseCase -.-> PasswordRecovery
AccountMongoRepository -.-> LoadAccountByEmailRepository
JwtAdapter -.-> TokenGenerator
EmailQueueAdapter -.-> EmailSender

@enduml
