@startuml "refresh-token"

package controllers {
    [RefreshTokenController] -up-> () Validator
    [refreshTokenValidator] -.-> () Validator
}

package domain {
    () RefreshToken
}

package usecase {
    () LoadAccountByEmailRepository <-- [RefreshTokenUseCase]
    () TokenDecoder <-- [RefreshTokenUseCase]
    () TokenSetGenerator <-- [RefreshTokenUseCase]
}

package gateway {
    [AccountMongoRepository]
    [JwtAdapter]
}

RefreshTokenController --> RefreshToken
RefreshTokenUseCase -.-> RefreshToken
AccountMongoRepository -.-> LoadAccountByEmailRepository
JwtAdapter -.-> TokenDecoder
JwtAdapter -.-> TokenSetGenerator

@enduml
