@startuml signup

package controllers {
  [SignUpController] -> () Validator
  [signUpValidator] -.-> () Validator
  [signUpValidator] -> () EmailValidator
}

package utils {
    [EmailValidatorAdapter]
}

package domain {
    () AddAccount
}

package usecase {
    () AddAccountRepository <-- [AddAccountUseCase]
    () Hasher <-- [AddAccountUseCase]
}

package gateway {
    [AccountMongoRepository]
    [BCryptAdapter]
}

EmailValidatorAdapter -.-> EmailValidator
SignUpController --> AddAccount
AddAccountUseCase -.-> AddAccount
AccountMongoRepository -.-> AddAccountRepository
BCryptAdapter -.-> Hasher

@enduml
